[toolchain]
# TODO: Switch to stable and add visionOS targets once https://github.com/rust-lang/compiler-team/issues/918 is done
channel = "nightly"
components = ["rust-src"]
targets = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "aarch64-apple-ios-macabi",
]
